//
//  String+Localization.swift
//  example
//
//  Path: Core/Localization/String+Localization.swift
//  Auto-generated on 02/20/26
//  ⚠️ DO NOT EDIT MANUALLY - This file is auto-generated by generate_localization.py
//

import Foundation

// MARK: - String Localization Extension
extension String {
    /// Auth.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func auth(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Auth")
    }
    
    /// Auth.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func auth(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Auth")
        return String(format: format, arguments: arguments)
    }
    /// Common.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func common(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Common")
    }
    
    /// Common.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func common(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Common")
        return String(format: format, arguments: arguments)
    }
    /// Error.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func error(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Error")
    }
    
    /// Error.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func error(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Error")
        return String(format: format, arguments: arguments)
    }
    /// ServerError.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func servererror(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "ServerError")
    }
    
    /// ServerError.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func servererror(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "ServerError")
        return String(format: format, arguments: arguments)
    }
}

// MARK: - Localized String Keys
/// 타입 안전한 다국어 키를 위한 네임스페이스
/// Total: 79 keys
enum Localized {

    // MARK: - Auth Keys (16 keys)
    enum Auth {
        // Login
        static let loginContinueWith = String.auth("login_continue_with")
        static let loginForgetPassword = String.auth("login_forget_password")
        static let loginNoAccount = String.auth("login_no_account")
        static let loginSubtitle = String.auth("login_subtitle")

        // Oauth
        static let oauthApple = String.auth("oauth_apple")
        static let oauthGoogle = String.auth("oauth_google")

        // Placeholder
        static let placeholderConfirmPassword = String.auth("placeholder_confirm_password")
        static let placeholderEmail = String.auth("placeholder_email")
        static let placeholderName = String.auth("placeholder_name")
        static let placeholderPassword = String.auth("placeholder_password")

        // Signup
        static let signupAgreeSuffix = String.auth("signup_agree_suffix")
        static let signupAnd = String.auth("signup_and")
        static let signupContinueWith = String.auth("signup_continue_with")
        static let signupPrivacyPolicy = String.auth("signup_privacy_policy")
        static let signupSubtitle = String.auth("signup_subtitle")
        static let signupTermsOfService = String.auth("signup_terms_of_service")
    }

    // MARK: - Common Keys (23 keys)
    enum Common {
        static let applicationName = String.common("application_name")
        static let back = String.common("back")
        static let cancel = String.common("cancel")
        static let close = String.common("close")
        static let confirm = String.common("confirm")
        static let delete = String.common("delete")
        static let done = String.common("done")
        static let edit = String.common("edit")
        static let email = String.common("email")
        static let error = String.common("error")
        static let loading = String.common("loading")
        static let login = String.common("login")
        static let logout = String.common("logout")
        static let name = String.common("name")
        static let next = String.common("next")
        static let ok = String.common("ok")
        static let password = String.common("password")
        static let retry = String.common("retry")
        static let save = String.common("save")
        static let signup = String.common("signup")
        static let submit = String.common("submit")
        static let switchToDarkMode = String.common("switch_to_dark_mode")
        static let switchToLightMode = String.common("switch_to_light_mode")
    }

    // MARK: - Error Keys (32 keys)
    enum Error {
        static let errorBadRequest = String.error("error_bad_request")
        static let errorCancelled = String.error("error_cancelled")
        static let errorDecoding = String.error("error_decoding")
        static let errorEmptyConfirmPassword = String.error("error_empty_confirm_password")
        static let errorEmptyEmail = String.error("error_empty_email")
        static let errorEmptyPassword = String.error("error_empty_password")
        static let errorEmptyUsername = String.error("error_empty_username")
        static let errorEncoding = String.error("error_encoding")
        static let errorForbidden = String.error("error_forbidden")
        static let errorInvalidEmail = String.error("error_invalid_email")
        static let errorInvalidUrl = String.error("error_invalid_url")
        static let errorLoginCancelled = String.error("error_login_cancelled")
        static let errorLoginFailed = String.error("error_login_failed")
        static let errorNameMinLength = String.error("error_name_min_length")
        static let errorNoConnection = String.error("error_no_connection")
        static let errorNoData = String.error("error_no_data")
        static let errorNotFound = String.error("error_not_found")
        static let errorOauthCallbackFailed = String.error("error_oauth_callback_failed")
        static let errorPasswordMismatch = String.error("error_password_mismatch")
        static let errorPasswordNoLowercase = String.error("error_password_no_lowercase")
        static let errorPasswordNoNumber = String.error("error_password_no_number")
        static let errorPasswordNoSpecialCharacter = String.error("error_password_no_special_character")
        static let errorPasswordNoUppercase = String.error("error_password_no_uppercase")
        static let errorRateLimited = String.error("error_rate_limited")
        static let errorRateLimitedWithRetry = String.error("error_rate_limited_with_retry")
        static let errorServer = String.error("error_server")
        static let errorSessionExpired = String.error("error_session_expired")
        static let errorSignupFailed = String.error("error_signup_failed")
        static let errorTimeout = String.error("error_timeout")
        static let errorUnauthorized = String.error("error_unauthorized")
        static let errorUnknown = String.error("error_unknown")
        static let errorWeakPassword = String.error("error_weak_password")
    }

    // MARK: - ServerError Keys (8 keys)
    enum ServerError {
        static let serverAuthCodeInvalid = String.servererror("server_auth_code_invalid")
        static let serverAuthCredentialsInvalid = String.servererror("server_auth_credentials_invalid")
        static let serverAuthProviderUnsupported = String.servererror("server_auth_provider_unsupported")
        static let serverAuthSessionInvalid = String.servererror("server_auth_session_invalid")
        static let serverAuthSessionNotFound = String.servererror("server_auth_session_not_found")
        static let serverOauthFailed = String.servererror("server_oauth_failed")
        static let serverUserAlreadyExists = String.servererror("server_user_already_exists")
        static let serverUserNotFound = String.servererror("server_user_not_found")
    }
}
