//
//  String+Localization.swift
//  example
//
//  Path: Core/Localization/String+Localization.swift
//  Auto-generated on 01/07/26
//  ⚠️ DO NOT EDIT MANUALLY - This file is auto-generated by generate_localization.py
//

import Foundation

// MARK: - String Localization Extension
extension String {
    /// Auth.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func auth(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Auth")
    }
    
    /// Auth.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func auth(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Auth")
        return String(format: format, arguments: arguments)
    }
    /// Common.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func common(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Common")
    }
    
    /// Common.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func common(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Common")
        return String(format: format, arguments: arguments)
    }
    /// Error.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func error(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "Error")
    }
    
    /// Error.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func error(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "Error")
        return String(format: format, arguments: arguments)
    }
    /// ServerError.xcstrings에서 문자열 가져오기
    /// - Parameter key: 다국어 키
    /// - Returns: 현재 언어로 번역된 문자열
    static func servererror(_ key: String) -> String {
        String(localized: String.LocalizationValue(key), table: "ServerError")
    }
    
    /// ServerError.xcstrings에서 문자열 가져오기 (파라미터 포함)
    /// - Parameters:
    ///   - key: 다국어 키
    ///   - arguments: 문자열에 삽입할 값들
    /// - Returns: 현재 언어로 번역되고 파라미터가 삽입된 문자열
    static func servererror(_ key: String, _ arguments: CVarArg...) -> String {
        let format = String(localized: String.LocalizationValue(key), table: "ServerError")
        return String(format: format, arguments: arguments)
    }
}

// MARK: - Localized String Keys
/// 타입 안전한 다국어 키를 위한 네임스페이스
/// Total: 59 keys
enum Localized {

    // MARK: - Auth Keys (24 keys)
    enum Auth {
        // Login
        static let loginContinueWith = String.auth("login_continue_with")
        static let loginRememberMe = String.auth("login_remember_me")
        static let loginSubtitle = String.auth("login_subtitle")
        static let loginTitle = String.auth("login_title")

        // Oauth
        static let oauthApple = String.auth("oauth_apple")
        static let oauthGoogle = String.auth("oauth_google")

        // Placeholder
        static let placeholderConfirmPasswordPlaceholder = String.auth("placeholder_confirm_password_placeholder")
        static let placeholderEmailPlaceholder = String.auth("placeholder_email_placeholder")
        static let placeholderNamePlaceholder = String.auth("placeholder_name_placeholder")
        static let placeholderPasswordPlaceholder = String.auth("placeholder_password_placeholder")

        // Signup
        static let signupContinueWith = String.auth("signup_continue_with")
        static let signupSubtitle = String.auth("signup_subtitle")
        static let signupTitle = String.auth("signup_title")

        // Validation
        static let validationConfirmPasswordEmpty = String.auth("validation_confirm_password_empty")
        static let validationEmailEmpty = String.auth("validation_email_empty")
        static let validationEmailInvalid = String.auth("validation_email_invalid")
        static let validationNameEmpty = String.auth("validation_name_empty")
        static let validationNameMinLength = String.auth("validation_name_min_length")
        static let validationPasswordEmpty = String.auth("validation_password_empty")
        static let validationPasswordMinLength = String.auth("validation_password_min_length")
        static let validationPasswordNoLowercase = String.auth("validation_password_no_lowercase")
        static let validationPasswordNoNumber = String.auth("validation_password_no_number")
        static let validationPasswordNoUppercase = String.auth("validation_password_no_uppercase")
        static let validationPasswordsNotMatch = String.auth("validation_passwords_not_match")
    }

    // MARK: - Common Keys (19 keys)
    enum Common {
        static let applicationName = String.common("application_name")
        static let back = String.common("back")
        static let cancel = String.common("cancel")
        static let close = String.common("close")
        static let confirm = String.common("confirm")
        static let delete = String.common("delete")
        static let done = String.common("done")
        static let edit = String.common("edit")
        static let email = String.common("email")
        static let loading = String.common("loading")
        static let login = String.common("login")
        static let logout = String.common("logout")
        static let next = String.common("next")
        static let ok = String.common("ok")
        static let password = String.common("password")
        static let retry = String.common("retry")
        static let save = String.common("save")
        static let signup = String.common("signup")
        static let submit = String.common("submit")
    }

    // MARK: - Error Keys (9 keys)
    enum Error {
        static let errorDecoding = String.error("error_decoding")
        static let errorEncoding = String.error("error_encoding")
        static let errorInvalidUrl = String.error("error_invalid_url")
        static let errorLoginCancelled = String.error("error_login_cancelled")
        static let errorLoginFailed = String.error("error_login_failed")
        static let errorNoData = String.error("error_no_data")
        static let errorOauthCallbackFailed = String.error("error_oauth_callback_failed")
        static let errorSignupFailed = String.error("error_signup_failed")
        static let errorUnknown = String.error("error_unknown")
    }

    // MARK: - ServerError Keys (7 keys)
    enum ServerError {
        static let serverAuthCodeInvalid = String.servererror("server_auth_code_invalid")
        static let serverAuthCredentialsInvalid = String.servererror("server_auth_credentials_invalid")
        static let serverAuthProviderUnsupported = String.servererror("server_auth_provider_unsupported")
        static let serverAuthSessionInvalid = String.servererror("server_auth_session_invalid")
        static let serverAuthSessionNotFound = String.servererror("server_auth_session_not_found")
        static let serverUserAlreadyExists = String.servererror("server_user_already_exists")
        static let serverUserNotFound = String.servererror("server_user_not_found")
    }
}
